apiVersion: v1
kind: Service
metadata:
  name: {{ include "digger-drift.fullname" . }}
  labels:
    {{- include "digger-drift.labels" . | nindent 4 }}
spec:
  type: {{ .Values.drift.service.type }}
  ports:
    - port: {{ .Values.drift.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "digger-drift.selectorLabels" . | nindent 4 }}

