apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "digger-backend.fullname" . }}-web
  labels:
    {{- include "digger-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.digger.replicaCount }}
  selector:
    matchLabels:
      app: digger-backend-web
  template:
    metadata:
      labels:
        app: digger-backend-web
        {{- include "digger-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: web
        image: "{{ .Values.digger.image.repository }}:{{ .Values.digger.image.tag }}"
        imagePullPolicy: {{ .Values.digger.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        {{- if .Values.digger.secret.useExistingSecret }}
        envFrom:
        - secretRef:
            name: {{ .Values.digger.secret.existingSecretName }}
        {{- else }}
        envFrom:
        - secretRef:
            name: {{ include "digger-backend.fullname" . }}-secret
        {{- end }}
        {{- if .Values.digger.customEnv }}
        env:
        {{- toYaml .Values.digger.customEnv | nindent 10 }}
        {{- end }}
        {{- if .Values.digger.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.digger.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.digger.startupProbe }}
        startupProbe:
          {{- toYaml .Values.digger.startupProbe | nindent 10 }}
        {{- end }}
        {{- with .Values.digger.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.digger.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.digger.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.digger.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
