apiVersion: v1
kind: Service
metadata:
  name: {{ include "taco-token-service.fullname" . }}
  labels:
    {{- include "taco-token-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tokenService.service.type }}
  ports:
    - port: {{ .Values.tokenService.service.port }}
      targetPort: {{ .Values.tokenService.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "taco-token-service.selectorLabels" . | nindent 4 }}

