---
name: release cli

"on":
  release:
    branches:
      - 'go'
    types:
      - 'released'

jobs:
  binary:
    if: "!startsWith(github.event.release.tag_name, 'taco/')"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Publish linux-x64 exec to github
        id: build-and-release-binary
        uses: wangyoucao577/go-release-action@8fa1e8368c8465264d64e0198208e10f71474c87  # v1.50
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          goversion: 1.25.4
          project_path: ./cli/cmd/digger
          binary_name: digger
          pre_command: export CGO_ENABLED=0
          ldflags: ${{ matrix.ldflags }}
          sha256sum: true
          md5sum: false
          asset_name: "digger-cli-Linux-X64"
          compress_assets: "OFF"
