# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy drift backend
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: Deploy drift backend
    runs-on: ubuntu-latest
    concurrency: drift-deploy    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly-drift.toml

        env:
          FLY_API_TOKEN: ${{ secrets.FLYIO_DRIFT_TOKEN }}
