---
name: release ee cli

"on":
  release:
    branches:
      - 'go'
    types:
      - 'released'

jobs:
  binary:
    runs-on: ubuntu-latest

    steps:
      - name: Download Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0
        id: go

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Publish linux-x64 exec to github
        id: build-and-release-binary
        uses: wangyoucao577/go-release-action@8fa1e8368c8465264d64e0198208e10f71474c87  # v1.50
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          goversion: 1.24.0
          project_path: ./ee/cli/cmd/digger
          binary_name: digger
          pre_command: export CGO_ENABLED=0
          ldflags: ${{ matrix.ldflags }}
          sha256sum: true
          md5sum: false
          asset_name: "digger-ee-cli-Linux-X64-fips"
          compress_assets: "OFF"
        env:
          GODEBUG: fips140=only
          GOFIPS140: v1.0.0

