# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy projects-refresh-service
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: Deploy pro app
    runs-on: ubuntu-latest
    concurrency: pro-deploy    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly-pro.toml

        env:
          FLY_API_TOKEN: ${{ secrets.FLYIO_PRO_TOKEN }}
